### ISSUE TITLE
how report.html be designed?

### ISSUE THREAD

**Issue by wasonal** [discoveryjs/cpupro#4]
how report.html be designed?
Or how to covert cpuprofile to a list like
Array<{
  costTime: number,
  functionName: string,
}>

**Comment by lahmatiy** [comment]
It's build with [Discovery.js](https://github.com/discoveryjs/discovery), its source can be found in [app](https://github.com/lahmatiy/cpupro/tree/main/app) folder. You can run it locally with `npm start` command in the cloned repo.

If you need a subset of data, open a report page:
<img width="400" alt="make report button" src="https://github.com/lahmatiy/cpupro/assets/270491/fd4c1131-b832-4b6c-9288-bb9b7b14aac8">
Write a query and copy JSON using "f" button:
<img width="1004" alt="query" src="https://github.com/lahmatiy/cpupro/assets/270491/149b44a2-f21d-412b-827a-92d67bd84c8d">
Query example:
```js
functions.({
  name,
  loc,
  selfTime,
  totalTime
})
```
You also can customize view:
<img width="884" alt="image" src="https://github.com/lahmatiy/cpupro/assets/270491/e3f0d7cf-a904-4ef7-8769-04c3067bbf4a">
Or just click "as table" in struct view:
<img width="894" alt="image" src="https://github.com/lahmatiy/cpupro/assets/270491/0bf8ea35-50a2-4b5d-a66e-2514744001b9">
Also you can use this [link](https://lahmatiy.github.io/cpupro/#report&q=ZnVuY3Rpb25zLih7CiAgbmFtZSwKICBsb2MsCiAgc2VsZlRpbWUsCiAgdG90YWxUaW1lCn0p) with prefilled query, just load you profile file using "Open file..." in top right corner.
